import {
  InternalUser,
  PermissionKey,
  RoleDefinition,
} from '@/types/domain/bos';

export const ALL_PERMISSIONS: {
  key: PermissionKey;
  module: string;
  action: 'View' | 'Create' | 'Edit' | 'Approve' | 'Export';
  description: string;
}[] = [
  { key: 'dashboard.view', module: 'Dashboard', action: 'View', description: 'Access operational command center' },
  { key: 'orders.view', module: 'Orders', action: 'View', description: 'View institutional and retail orders' },
  { key: 'orders.create', module: 'Orders', action: 'Create', description: 'Create new customer orders' },
  { key: 'orders.edit', module: 'Orders', action: 'Edit', description: 'Modify order quantities and schedules' },
  { key: 'orders.approve', module: 'Orders', action: 'Approve', description: 'Approve institutional credit or price overrides' },
  { key: 'orders.export', module: 'Orders', action: 'Export', description: 'Export order manifests and schedules' },
  { key: 'fulfillment.view', module: 'Fulfillment', action: 'View', description: 'View picking, packing, and staging queues' },
  { key: 'fulfillment.manage', module: 'Fulfillment', action: 'Edit', description: 'Advance orders through picking and packing' },
  { key: 'customers.view', module: 'Customers', action: 'View', description: 'View customers and institutional contracts' },
  { key: 'customers.create', module: 'Customers', action: 'Create', description: 'Onboard new customers and institutions' },
  { key: 'customers.edit', module: 'Customers', action: 'Edit', description: 'Update customer terms and contacts' },
  { key: 'products.view', module: 'Products', action: 'View', description: 'View product catalog and pricing tiers' },
  { key: 'products.create', module: 'Products', action: 'Create', description: 'Add new SKUs to the catalog' },
  { key: 'products.edit', module: 'Products', action: 'Edit', description: 'Edit multi-tier product prices and units' },
  { key: 'inventory.view', module: 'Inventory', action: 'View', description: 'View warehouse stock, FEFO batches, and expiry' },
  { key: 'inventory.receive', module: 'Inventory', action: 'Create', description: 'Receive goods and post stock batches' },
  { key: 'inventory.adjust', module: 'Inventory', action: 'Edit', description: 'Record stock counts, wastage, and adjustments' },
  { key: 'inventory.transfer', module: 'Inventory', action: 'Edit', description: 'Transfer stock across warehouse zones' },
  { key: 'procurement.view', module: 'Procurement', action: 'View', description: 'View purchase requests, POs, and GRNs' },
  { key: 'procurement.create', module: 'Procurement', action: 'Create', description: 'Raise purchase requests and purchase orders' },
  { key: 'procurement.approve', module: 'Procurement', action: 'Approve', description: 'Approve purchase orders and supplier spend' },
  { key: 'suppliers.view', module: 'Suppliers', action: 'View', description: 'View supplier directory and price history' },
  { key: 'suppliers.create', module: 'Suppliers', action: 'Create', description: 'Register new farm cooperatives and vendors' },
  { key: 'suppliers.edit', module: 'Suppliers', action: 'Edit', description: 'Update supplier lead times and price lists' },
  { key: 'deliveries.view', module: 'Deliveries', action: 'View', description: 'View delivery runs, routes, and POD status' },
  { key: 'deliveries.assign', module: 'Deliveries', action: 'Edit', description: 'Assign drivers and vehicles to routes' },
  { key: 'deliveries.dispatch', module: 'Deliveries', action: 'Approve', description: 'Confirm dispatch and capture Proof of Delivery' },
  { key: 'finance.view', module: 'Finance', action: 'View', description: 'View AR, AP, invoices, and financial ledgers' },
  { key: 'finance.record_payment', module: 'Finance', action: 'Create', description: 'Record customer receipts and supplier payments' },
  { key: 'finance.allocate_payment', module: 'Finance', action: 'Edit', description: 'Allocate payments against open invoices' },
  { key: 'finance.reconcile', module: 'Finance', action: 'Approve', description: 'Reconcile M-Pesa and bank statements' },
  { key: 'crm.view', module: 'CRM', action: 'View', description: 'View institutional contacts, tickets, and renewals' },
  { key: 'crm.manage', module: 'CRM', action: 'Edit', description: 'Log follow-ups, resolve complaints, manage contracts' },
  { key: 'reports.view', module: 'Reports', action: 'View', description: 'View operational and financial analytics' },
  { key: 'reports.export', module: 'Reports', action: 'Export', description: 'Export analytical reports to CSV' },
  { key: 'approvals.view', module: 'Approvals', action: 'View', description: 'Access centralized approval inbox' },
  { key: 'approvals.approve', module: 'Approvals', action: 'Approve', description: 'Approve or reject governed operational requests' },
  { key: 'documents.view', module: 'Documents', action: 'View', description: 'View invoices, GRNs, PODs, and certificates' },
  { key: 'documents.manage', module: 'Documents', action: 'Create', description: 'Upload and verify operational documents' },
  { key: 'administration.users.view', module: 'Administration', action: 'View', description: 'View internal employee directory' },
  { key: 'administration.users.create', module: 'Administration', action: 'Create', description: 'Invite new internal members' },
  { key: 'administration.users.edit', module: 'Administration', action: 'Edit', description: 'Activate, suspend, or disable user accounts' },
  { key: 'administration.roles.view', module: 'Administration', action: 'View', description: 'View RBAC roles and permission mappings' },
  { key: 'administration.roles.manage', module: 'Administration', action: 'Edit', description: 'Modify role permissions and create roles' },
  { key: 'audit.view', module: 'Audit Logs', action: 'View', description: 'Inspect immutable system audit trail' },
];

export const DEFAULT_ROLES: RoleDefinition[] = [
  {
    id: 'executive',
    name: 'Business Owner / Executive',
    description: 'Full visibility across revenue, margins, receivables, payables, inventory value, approvals, and audit trails.',
    defaultFocus: 'Executive Margin, Cash Flow & Governance Overview',
    lastModified: '2026-09-28',
    permissions: [
      'dashboard.view',
      'orders.view',
      'orders.approve',
      'orders.export',
      'fulfillment.view',
      'customers.view',
      'products.view',
      'inventory.view',
      'procurement.view',
      'procurement.approve',
      'suppliers.view',
      'deliveries.view',
      'finance.view',
      'finance.reconcile',
      'crm.view',
      'reports.view',
      'reports.export',
      'approvals.view',
      'approvals.approve',
      'documents.view',
      'administration.users.view',
      'administration.roles.view',
      'audit.view',
    ],
  },
  {
    id: 'operations_manager',
    name: 'Operations Manager',
    description: 'End-to-end command of order fulfillment, warehouse stock, procurement pipelines, delivery dispatch, and operational approvals.',
    defaultFocus: 'Fulfillment SLA, FEFO Risk & Dispatch Control',
    lastModified: '2026-09-29',
    permissions: [
      'dashboard.view',
      'orders.view',
      'orders.create',
      'orders.edit',
      'orders.approve',
      'orders.export',
      'fulfillment.view',
      'fulfillment.manage',
      'customers.view',
      'products.view',
      'products.edit',
      'inventory.view',
      'inventory.receive',
      'inventory.adjust',
      'inventory.transfer',
      'procurement.view',
      'procurement.create',
      'procurement.approve',
      'suppliers.view',
      'suppliers.edit',
      'deliveries.view',
      'deliveries.assign',
      'deliveries.dispatch',
      'crm.view',
      'crm.manage',
      'reports.view',
      'reports.export',
      'approvals.view',
      'approvals.approve',
      'documents.view',
      'documents.manage',
    ],
  },
  {
    id: 'sales_rep',
    name: 'Sales Representative',
    description: 'Manages institutional accounts, school/hospital/hotel tenders, customer orders, contract renewals, and CRM follow-ups.',
    defaultFocus: 'Institutional Orders, Contracts & Client Follow-ups',
    lastModified: '2026-09-24',
    permissions: [
      'dashboard.view',
      'orders.view',
      'orders.create',
      'orders.edit',
      'orders.export',
      'fulfillment.view',
      'customers.view',
      'customers.create',
      'customers.edit',
      'products.view',
      'inventory.view',
      'deliveries.view',
      'crm.view',
      'crm.manage',
      'documents.view',
    ],
  },
  {
    id: 'procurement_officer',
    name: 'Procurement Officer',
    description: 'Manages farm cooperatives, vendor pricing, purchase requests, purchase orders, receiving coordination, and reorder thresholds.',
    defaultFocus: 'Purchase Requests, Supplier Prices & Replenishment',
    lastModified: '2026-09-27',
    permissions: [
      'dashboard.view',
      'products.view',
      'products.create',
      'products.edit',
      'inventory.view',
      'inventory.receive',
      'procurement.view',
      'procurement.create',
      'suppliers.view',
      'suppliers.create',
      'suppliers.edit',
      'reports.view',
      'documents.view',
      'documents.manage',
    ],
  },
  {
    id: 'storekeeper',
    name: 'Storekeeper',
    description: 'Controls cold-chain and dry-bulk warehouses, FEFO stock batches, GRN receiving, order picking/packing, and wastage logs.',
    defaultFocus: 'Warehouse Stock, FEFO Expiry, Receiving & Picking',
    lastModified: '2026-09-26',
    permissions: [
      'dashboard.view',
      'orders.view',
      'fulfillment.view',
      'fulfillment.manage',
      'products.view',
      'inventory.view',
      'inventory.receive',
      'inventory.adjust',
      'inventory.transfer',
      'procurement.view',
      'deliveries.view',
      'documents.view',
      'documents.manage',
    ],
  },
  {
    id: 'accounts_clerk',
    name: 'Accounts Clerk',
    description: 'Handles customer invoicing, M-Pesa/EFT payment recording, invoice allocations, and daily billing documentation.',
    defaultFocus: 'Invoicing, Payment Recording & AR Allocations',
    lastModified: '2026-09-21',
    permissions: [
      'dashboard.view',
      'orders.view',
      'customers.view',
      'suppliers.view',
      'finance.view',
      'finance.record_payment',
      'finance.allocate_payment',
      'documents.view',
      'documents.manage',
    ],
  },
  {
    id: 'finance_manager',
    name: 'Finance Manager',
    description: 'Oversees Accounts Receivable, Accounts Payable, cash flow, bank reconciliation, credit approvals, and financial reporting.',
    defaultFocus: 'Receivables Aging, Payables, Cash Flow & Reconciliation',
    lastModified: '2026-09-29',
    permissions: [
      'dashboard.view',
      'orders.view',
      'orders.approve',
      'customers.view',
      'customers.edit',
      'products.view',
      'inventory.view',
      'procurement.view',
      'procurement.approve',
      'suppliers.view',
      'finance.view',
      'finance.record_payment',
      'finance.allocate_payment',
      'finance.reconcile',
      'reports.view',
      'reports.export',
      'approvals.view',
      'approvals.approve',
      'documents.view',
      'documents.manage',
      'audit.view',
    ],
  },
  {
    id: 'delivery_driver',
    name: 'Delivery Driver',
    description: 'Executes assigned route runs, inspects loaded orders, updates dispatch status, and captures electronic Proof of Delivery (POD).',
    defaultFocus: 'Assigned Delivery Runs, Route Manifests & POD Capture',
    lastModified: '2026-09-20',
    permissions: [
      'dashboard.view',
      'orders.view',
      'fulfillment.view',
      'deliveries.view',
      'deliveries.dispatch',
      'documents.view',
      'documents.manage',
    ],
  },
  {
    id: 'administrator',
    name: 'Administrator',
    description: 'System governance, administrator-controlled member onboarding, role & permission matrix management, and security audit logs.',
    defaultFocus: 'Identity Governance, Role Matrix & System Audit',
    lastModified: '2026-09-30',
    permissions: ALL_PERMISSIONS.map((p) => p.key),
  },
];

export function getRolePermissions(
  roleId: string,
  roles: RoleDefinition[] = DEFAULT_ROLES
): PermissionKey[] {
  const role = roles.find((r) => r.id === roleId);
  return role ? role.permissions : ['dashboard.view'];
}

export function hasPermission(
  user: InternalUser | null | undefined,
  permission: PermissionKey,
  roles: RoleDefinition[] = DEFAULT_ROLES
): boolean {
  if (!user || user.status !== 'Active') return false;
  const perms = getRolePermissions(user.roleId, roles);
  return perms.includes(permission);
}

export function hasAnyPermission(
  user: InternalUser | null | undefined,
  permissions: PermissionKey[],
  roles: RoleDefinition[] = DEFAULT_ROLES
): boolean {
  return permissions.some((p) => hasPermission(user, p, roles));
}

export const ROUTE_REQUIRED_PERMISSION: Record<string, PermissionKey> = {
  '/dashboard': 'dashboard.view',
  '/orders': 'orders.view',
  '/fulfillment': 'fulfillment.view',
  '/deliveries': 'deliveries.view',
  '/customers': 'customers.view',
  '/institutions': 'customers.view',
  '/crm': 'crm.view',
  '/products': 'products.view',
  '/inventory': 'inventory.view',
  '/procurement': 'procurement.view',
  '/suppliers': 'suppliers.view',
  '/invoices': 'finance.view',
  '/payments': 'finance.view',
  '/finance': 'finance.view',
  '/reports': 'reports.view',
  '/approvals': 'approvals.view',
  '/documents': 'documents.view',
  '/administration/users': 'administration.users.view',
  '/administration/roles': 'administration.roles.view',
  '/administration/audit-logs': 'audit.view',
  '/audit-logs': 'audit.view',
  '/settings': 'dashboard.view',
  '/profile': 'dashboard.view',
};
