import {
  ApprovalRequestRecord,
  AuditLogRecord,
  CrmTicketRecord,
  CustomerInstitutionRecord,
  DeliveryRunRecord,
  DocumentRecord,
  InternalUser,
  InvoiceRecord,
  NotificationItem,
  OrderRecord,
  PaymentRecord,
  ProcurementOrderRecord,
  ProductRecord,
  StockBatchRecord,
  StockMovementRecord,
  SupplierRecord,
  WarehouseRecord,
} from '@/types/domain/bos';

export const IMAGE_PATHS = {
  loginHero: '/src/assets/images/login_agro_distribution_1790804280633.jpg',
  freshProduce: '/src/assets/images/product_fresh_produce_1790804292232.jpg',
  dryGrains: '/src/assets/images/product_dry_grains_1790804302244.jpg',
  warehouseColdChain: '/src/assets/images/warehouse_cold_chain_1790804313272.jpg',
};

export const INITIAL_USERS: InternalUser[] = [
  {
    id: 'USR-009',
    email: 'v.kinyua@agrodeliveries.co.ke',
    fullName: 'Victor Kinyua',
    nickname: 'Victor',
    roleId: 'administrator',
    roleName: 'Administrator',
    status: 'Active',
    department: 'Systems & Security Governance',
    branch: 'Nairobi Central Hub',
    phone: '+254 724 800 990',
    lastActiveAt: '2026-10-01 09:25 EAT',
    invitedBy: 'System Bootstrap',
  },
  {
    id: 'USR-001',
    email: 'w.mwangi@agrodeliveries.co.ke',
    fullName: 'Wanjiku Mwangi',
    nickname: 'Shiku',
    roleId: 'executive',
    roleName: 'Business Owner / Executive',
    status: 'Active',
    department: 'Executive Directorate',
    branch: 'Nairobi Central Hub',
    phone: '+254 722 410 101',
    lastActiveAt: '2026-10-01 09:20 EAT',
    invitedBy: 'System Bootstrap',
  },
  {
    id: 'USR-002',
    email: 'd.kiprop@agrodeliveries.co.ke',
    fullName: 'Daniel Kiprop',
    nickname: 'Dan',
    roleId: 'operations_manager',
    roleName: 'Operations Manager',
    status: 'Active',
    department: 'Fulfillment & Operations',
    branch: 'Nairobi Central Hub',
    phone: '+254 733 518 204',
    lastActiveAt: '2026-10-01 09:18 EAT',
    invitedBy: 'Wanjiku Mwangi',
  },
  {
    id: 'USR-003',
    email: 'g.achieng@agrodeliveries.co.ke',
    fullName: 'Grace Achieng',
    nickname: 'Grace',
    roleId: 'sales_rep',
    roleName: 'Sales Representative',
    status: 'Active',
    department: 'Institutional Sales & Tenders',
    branch: 'Westlands Desk',
    phone: '+254 711 890 332',
    lastActiveAt: '2026-10-01 08:55 EAT',
    invitedBy: 'Daniel Kiprop',
  },
  {
    id: 'USR-004',
    email: 'p.ndungu@agrodeliveries.co.ke',
    fullName: 'Peter Ndung’u',
    nickname: 'Pete',
    roleId: 'procurement_officer',
    roleName: 'Procurement Officer',
    status: 'Active',
    department: 'Farm & Cooperative Sourcing',
    branch: 'Nairobi Central Hub',
    phone: '+254 720 644 719',
    lastActiveAt: '2026-10-01 08:40 EAT',
    invitedBy: 'Daniel Kiprop',
  },
  {
    id: 'USR-005',
    email: 's.mutua@agrodeliveries.co.ke',
    fullName: 'Samuel Mutua',
    nickname: 'Sam',
    roleId: 'storekeeper',
    roleName: 'Storekeeper',
    status: 'Active',
    department: 'Cold Chain & Dry Bulk Stores',
    branch: 'Nairobi Cold Hub A',
    phone: '+254 728 312 908',
    lastActiveAt: '2026-10-01 09:10 EAT',
    invitedBy: 'Daniel Kiprop',
  },
  {
    id: 'USR-006',
    email: 'f.chebet@agrodeliveries.co.ke',
    fullName: 'Faith Chebet',
    nickname: 'Faith',
    roleId: 'accounts_clerk',
    roleName: 'Accounts Clerk',
    status: 'Active',
    department: 'Billing & Settlements',
    branch: 'Nairobi Central Hub',
    phone: '+254 715 203 441',
    lastActiveAt: '2026-10-01 09:05 EAT',
    invitedBy: 'Mercy Kamau',
  },
  {
    id: 'USR-007',
    email: 'm.kamau@agrodeliveries.co.ke',
    fullName: 'Mercy Kamau',
    nickname: 'Mercy',
    roleId: 'finance_manager',
    roleName: 'Finance Manager',
    status: 'Active',
    department: 'Finance & Treasury',
    branch: 'Nairobi Central Hub',
    phone: '+254 721 908 112',
    lastActiveAt: '2026-10-01 09:12 EAT',
    invitedBy: 'Wanjiku Mwangi',
  },
  {
    id: 'USR-008',
    email: 'j.omondi@agrodeliveries.co.ke',
    fullName: 'Joseph Omondi',
    nickname: 'Joe',
    roleId: 'delivery_driver',
    roleName: 'Delivery Driver',
    status: 'Active',
    department: 'Fleet & Last-Mile Logistics',
    branch: 'Nairobi Cold Hub A',
    phone: '+254 701 445 872',
    lastActiveAt: '2026-10-01 07:45 EAT',
    invitedBy: 'Daniel Kiprop',
  },
  {
    id: 'USR-010',
    email: 'b.otieno@agrodeliveries.co.ke',
    fullName: 'Brian Otieno',
    nickname: 'Brian',
    roleId: 'storekeeper',
    roleName: 'Storekeeper',
    status: 'Suspended',
    department: 'Cold Chain & Dry Bulk Stores',
    branch: 'Embakasi Dry Bulk B',
    phone: '+254 719 551 200',
    lastActiveAt: '2026-09-19 17:12 EAT',
    invitedBy: 'Victor Kinyua',
  },
];

export const INITIAL_WAREHOUSES: WarehouseRecord[] = [
  {
    id: 'WH-01',
    code: 'NBO-COLD-A',
    name: 'Nairobi Cold Hub A',
    location: 'Industrial Area, Enterprise Rd, Nairobi',
    zoneType: 'Cold Chain (2°C - 6°C)',
    utilizationPct: 78.4,
    binsCount: 64,
    manager: 'Samuel Mutua',
  },
  {
    id: 'WH-02',
    code: 'EMB-DRY-B',
    name: 'Embakasi Dry Bulk B',
    location: 'Mombasa Rd ICD Corridor, Nairobi',
    zoneType: 'Ambient Dry Bulk',
    utilizationPct: 84.1,
    binsCount: 120,
    manager: 'Samuel Mutua',
  },
  {
    id: 'WH-03',
    code: 'WST-DOCK-C',
    name: 'Westlands Cross-Dock C',
    location: 'Waiyaki Way Hospitality Hub, Nairobi',
    zoneType: 'Cross-Dock Staging',
    utilizationPct: 61.5,
    binsCount: 36,
    manager: 'Daniel Kiprop',
  },
];

export const INITIAL_PRODUCTS: ProductRecord[] = [
  {
    id: 'PRD-001',
    sku: 'AG-VEG-001',
    name: 'Kinangop Roma Tomatoes (Grade 1)',
    category: 'Fresh Vegetables',
    unit: 'kilograms',
    description: 'Firm, vine-ripened highland Roma tomatoes sorted for institutional kitchens and hospitality catering.',
    imageUrl: IMAGE_PATHS.freshProduce,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 1420,
    reservedQty: 380,
    incomingQty: 600,
    reorderPoint: 500,
    pricing: {
      retailKes: 135,
      onlineKes: 130,
      wholesaleKes: 112,
      institutionalKes: 105,
      supplierCostKes: 78,
    },
    priceHistory: [
      { date: '2026-05-15', tier: 'Supplier Cost', priceKes: 65, changedBy: 'Peter Ndung’u' },
      { date: '2026-06-20', tier: 'Supplier Cost', priceKes: 68, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-22', tier: 'Supplier Cost', priceKes: 70, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-15', tier: 'Supplier Cost', priceKes: 72, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-20', tier: 'Supplier Cost', priceKes: 78, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-25', tier: 'Institutional', priceKes: 105, changedBy: 'Daniel Kiprop' },
    ],
  },
  {
    id: 'PRD-002',
    sku: 'AG-FRT-004',
    name: 'Murang’a Hass Avocados (Export Grade)',
    category: 'Fruits & Orchard',
    unit: 'pieces',
    description: 'Uniform 220g–260g oil-rich Hass avocados graded for hotels, hospitals, and retail packs.',
    imageUrl: IMAGE_PATHS.freshProduce,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 2850,
    reservedQty: 650,
    incomingQty: 1200,
    reorderPoint: 1000,
    pricing: {
      retailKes: 45,
      onlineKes: 42,
      wholesaleKes: 34,
      institutionalKes: 30,
      supplierCostKes: 21,
    },
    priceHistory: [
      { date: '2026-05-18', tier: 'Supplier Cost', priceKes: 18, changedBy: 'Peter Ndung’u' },
      { date: '2026-06-25', tier: 'Supplier Cost', priceKes: 19, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-20', tier: 'Supplier Cost', priceKes: 20, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-15', tier: 'Supplier Cost', priceKes: 20, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-10', tier: 'Supplier Cost', priceKes: 21, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-22', tier: 'Institutional', priceKes: 30, changedBy: 'Grace Achieng' },
    ],
  },
  {
    id: 'PRD-003',
    sku: 'AG-GRN-012',
    name: 'Organic Sukuma Wiki (Collard Greens)',
    category: 'Herbs & Greens',
    unit: 'bunches',
    description: '500g standardized field-chilled bunches harvested daily from Kiambu peri-urban farms.',
    imageUrl: IMAGE_PATHS.freshProduce,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 310,
    reservedQty: 240,
    incomingQty: 500,
    reorderPoint: 400,
    pricing: {
      retailKes: 50,
      onlineKes: 48,
      wholesaleKes: 38,
      institutionalKes: 35,
      supplierCostKes: 22,
    },
    priceHistory: [
      { date: '2026-05-10', tier: 'Supplier Cost', priceKes: 26, changedBy: 'Peter Ndung’u' },
      { date: '2026-06-15', tier: 'Supplier Cost', priceKes: 24, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-22', tier: 'Supplier Cost', priceKes: 23, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-18', tier: 'Supplier Cost', priceKes: 21, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-28', tier: 'Supplier Cost', priceKes: 22, changedBy: 'Peter Ndung’u' },
    ],
  },
  {
    id: 'PRD-004',
    sku: 'AG-DRY-002',
    name: 'Mwea Aromatic Pishori Rice (50kg Sack)',
    category: 'Dry Grains & Cereals',
    unit: 'bags',
    description: 'Single-origin Grade 1 Mwea Pishori aromatic long-grain white rice in moisture-sealed 50kg polypropylene bags.',
    imageUrl: IMAGE_PATHS.dryGrains,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 185,
    reservedQty: 45,
    incomingQty: 100,
    reorderPoint: 80,
    pricing: {
      retailKes: 11800,
      onlineKes: 11600,
      wholesaleKes: 10900,
      institutionalKes: 10450,
      supplierCostKes: 9100,
    },
    priceHistory: [
      { date: '2026-04-15', tier: 'Supplier Cost', priceKes: 8600, changedBy: 'Peter Ndung’u' },
      { date: '2026-05-25', tier: 'Supplier Cost', priceKes: 8750, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-10', tier: 'Supplier Cost', priceKes: 8900, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-18', tier: 'Supplier Cost', priceKes: 9000, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-01', tier: 'Supplier Cost', priceKes: 9100, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-18', tier: 'Institutional', priceKes: 10450, changedBy: 'Mercy Kamau' },
    ],
  },
  {
    id: 'PRD-005',
    sku: 'AG-DRY-009',
    name: 'Fortified Sifted Maize Meal (24x2kg Bale)',
    category: 'Dry Grains & Cereals',
    unit: 'packs',
    description: 'KEBS-certified vitamin-fortified grade-1 sifted maize meal packed in institutional 48kg master bales.',
    imageUrl: IMAGE_PATHS.dryGrains,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 260,
    reservedQty: 90,
    incomingQty: 150,
    reorderPoint: 120,
    pricing: {
      retailKes: 4150,
      onlineKes: 4100,
      wholesaleKes: 3880,
      institutionalKes: 3720,
      supplierCostKes: 3290,
    },
    priceHistory: [
      { date: '2026-04-20', tier: 'Supplier Cost', priceKes: 3450, changedBy: 'Peter Ndung’u' },
      { date: '2026-06-15', tier: 'Supplier Cost', priceKes: 3380, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-22', tier: 'Supplier Cost', priceKes: 3320, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-25', tier: 'Supplier Cost', priceKes: 3300, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-18', tier: 'Supplier Cost', priceKes: 3290, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-14', tier: 'Institutional', priceKes: 3720, changedBy: 'Daniel Kiprop' },
    ],
  },
  {
    id: 'PRD-006',
    sku: 'AG-DRY-015',
    name: 'Limuru Farm Fresh Tray Eggs (30-Egg Tray)',
    category: 'Dairy & Cold Chain',
    unit: 'dozens',
    description: 'Large yellow-yolk graded poultry eggs supplied in sanitized pulp trays (2.5 dozen unit equivalent).',
    imageUrl: IMAGE_PATHS.freshProduce,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 410,
    reservedQty: 190,
    incomingQty: 300,
    reorderPoint: 250,
    pricing: {
      retailKes: 540,
      onlineKes: 530,
      wholesaleKes: 490,
      institutionalKes: 465,
      supplierCostKes: 395,
    },
    priceHistory: [
      { date: '2026-05-12', tier: 'Supplier Cost', priceKes: 370, changedBy: 'Peter Ndung’u' },
      { date: '2026-06-20', tier: 'Supplier Cost', priceKes: 380, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-28', tier: 'Supplier Cost', priceKes: 385, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-30', tier: 'Supplier Cost', priceKes: 390, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-26', tier: 'Supplier Cost', priceKes: 395, changedBy: 'Peter Ndung’u' },
    ],
  },
  {
    id: 'PRD-007',
    sku: 'AG-TUB-003',
    name: 'Nyandarua Shangi Potatoes (Washed & Graded)',
    category: 'Root & Tubers',
    unit: 'kilograms',
    description: 'Pre-washed medium-to-large Shangi potatoes ideal for school boarding kitchens and hotel commissaries.',
    imageUrl: IMAGE_PATHS.freshProduce,
    status: 'Active',
    batchTracked: true,
    expiryTracked: true,
    availableQty: 3400,
    reservedQty: 950,
    incomingQty: 2000,
    reorderPoint: 1200,
    pricing: {
      retailKes: 85,
      onlineKes: 82,
      wholesaleKes: 68,
      institutionalKes: 62,
      supplierCostKes: 46,
    },
    priceHistory: [
      { date: '2026-05-15', tier: 'Supplier Cost', priceKes: 52, changedBy: 'Peter Ndung’u' },
      { date: '2026-06-22', tier: 'Supplier Cost', priceKes: 49, changedBy: 'Peter Ndung’u' },
      { date: '2026-07-30', tier: 'Supplier Cost', priceKes: 48, changedBy: 'Peter Ndung’u' },
      { date: '2026-08-28', tier: 'Supplier Cost', priceKes: 45, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-24', tier: 'Supplier Cost', priceKes: 46, changedBy: 'Peter Ndung’u' },
      { date: '2026-09-21', tier: 'Institutional', priceKes: 62, changedBy: 'Grace Achieng' },
    ],
  },
];

export const INITIAL_STOCK_BATCHES: StockBatchRecord[] = [
  {
    id: 'BAT-901',
    batchNumber: 'LOT-2609-TOM-A1',
    productId: 'PRD-001',
    productName: 'Kinangop Roma Tomatoes (Grade 1)',
    sku: 'AG-VEG-001',
    unit: 'kilograms',
    warehouseId: 'WH-01',
    warehouseName: 'Nairobi Cold Hub A',
    binCode: 'C1-R02-B04',
    supplierName: 'Kinangop Highland Growers Co-op',
    receivedDate: '2026-09-26',
    expiryDate: '2026-10-03',
    daysToExpiry: 3,
    availableQty: 420,
    reservedQty: 280,
    unitCostKes: 78,
    fefoPriority: 1,
    status: 'Expiring Soon',
  },
  {
    id: 'BAT-902',
    batchNumber: 'LOT-2609-TOM-A2',
    productId: 'PRD-001',
    productName: 'Kinangop Roma Tomatoes (Grade 1)',
    sku: 'AG-VEG-001',
    unit: 'kilograms',
    warehouseId: 'WH-01',
    warehouseName: 'Nairobi Cold Hub A',
    binCode: 'C1-R02-B05',
    supplierName: 'Kinangop Highland Growers Co-op',
    receivedDate: '2026-09-29',
    expiryDate: '2026-10-08',
    daysToExpiry: 8,
    availableQty: 1000,
    reservedQty: 100,
    unitCostKes: 78,
    fefoPriority: 2,
    status: 'Nominal',
  },
  {
    id: 'BAT-903',
    batchNumber: 'LOT-2609-SKM-C1',
    productId: 'PRD-003',
    productName: 'Organic Sukuma Wiki (Collard Greens)',
    sku: 'AG-GRN-012',
    unit: 'bunches',
    warehouseId: 'WH-01',
    warehouseName: 'Nairobi Cold Hub A',
    binCode: 'C2-R01-B01',
    supplierName: 'Kiambu Peri-Urban Greens Collective',
    receivedDate: '2026-09-29',
    expiryDate: '2026-10-02',
    daysToExpiry: 2,
    availableQty: 310,
    reservedQty: 240,
    unitCostKes: 22,
    fefoPriority: 1,
    status: 'Expiring Soon',
  },
  {
    id: 'BAT-904',
    batchNumber: 'LOT-2609-AVO-M4',
    productId: 'PRD-002',
    productName: 'Murang’a Hass Avocados (Export Grade)',
    sku: 'AG-FRT-004',
    unit: 'pieces',
    warehouseId: 'WH-03',
    warehouseName: 'Westlands Cross-Dock C',
    binCode: 'W1-R04-B02',
    supplierName: 'Meru & Murang’a Orchard Union',
    receivedDate: '2026-09-27',
    expiryDate: '2026-10-06',
    daysToExpiry: 6,
    availableQty: 2850,
    reservedQty: 650,
    unitCostKes: 21,
    fefoPriority: 1,
    status: 'FEFO Priority',
  },
  {
    id: 'BAT-905',
    batchNumber: 'LOT-2608-RIC-P9',
    productId: 'PRD-004',
    productName: 'Mwea Aromatic Pishori Rice (50kg Sack)',
    sku: 'AG-DRY-002',
    unit: 'bags',
    warehouseId: 'WH-02',
    warehouseName: 'Embakasi Dry Bulk B',
    binCode: 'D4-R08-B12',
    supplierName: 'Mwea Pishori Rice Millers Ltd',
    receivedDate: '2026-08-20',
    expiryDate: '2027-02-20',
    daysToExpiry: 143,
    availableQty: 185,
    reservedQty: 45,
    unitCostKes: 9100,
    fefoPriority: 1,
    status: 'Nominal',
  },
  {
    id: 'BAT-906',
    batchNumber: 'LOT-2609-MZE-B2',
    productId: 'PRD-005',
    productName: 'Fortified Sifted Maize Meal (24x2kg Bale)',
    sku: 'AG-DRY-009',
    unit: 'packs',
    warehouseId: 'WH-02',
    warehouseName: 'Embakasi Dry Bulk B',
    binCode: 'D2-R03-B07',
    supplierName: 'Unga Bora Rift Millers',
    receivedDate: '2026-09-12',
    expiryDate: '2027-01-15',
    daysToExpiry: 107,
    availableQty: 260,
    reservedQty: 90,
    unitCostKes: 3290,
    fefoPriority: 1,
    status: 'Nominal',
  },
  {
    id: 'BAT-907',
    batchNumber: 'LOT-2609-POT-N1',
    productId: 'PRD-007',
    productName: 'Nyandarua Shangi Potatoes (Washed & Graded)',
    sku: 'AG-TUB-003',
    unit: 'kilograms',
    warehouseId: 'WH-01',
    warehouseName: 'Nairobi Cold Hub A',
    binCode: 'C3-R05-B09',
    supplierName: 'Kinangop Highland Growers Co-op',
    receivedDate: '2026-09-25',
    expiryDate: '2026-10-09',
    daysToExpiry: 9,
    availableQty: 3400,
    reservedQty: 950,
    unitCostKes: 46,
    fefoPriority: 1,
    status: 'FEFO Priority',
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovementRecord[] = [
  {
    id: 'MOV-301',
    timestamp: '2026-09-30 11:45 EAT',
    type: 'Order Pick',
    productName: 'Kinangop Roma Tomatoes (Grade 1)',
    batchNumber: 'LOT-2609-TOM-A1',
    quantityDelta: -280,
    unit: 'kilograms',
    fromLocation: 'Nairobi Cold Hub A · C1-R02-B04',
    toLocation: 'Dispatch Bay 02 (Order ORD-2026-884)',
    actorName: 'Samuel Mutua',
    reason: 'FEFO Pick for Nairobi West Hospital Kitchen',
  },
  {
    id: 'MOV-302',
    timestamp: '2026-09-30 09:15 EAT',
    type: 'Receipt (GRN)',
    productName: 'Organic Sukuma Wiki (Collard Greens)',
    batchNumber: 'LOT-2609-SKM-C1',
    quantityDelta: 550,
    unit: 'bunches',
    fromLocation: 'Kiambu Peri-Urban Greens Collective',
    toLocation: 'Nairobi Cold Hub A · C2-R01-B01',
    actorName: 'Samuel Mutua',
    reason: 'GRN-2026-412 Quality Checked (98.5% Pass)',
  },
  {
    id: 'MOV-303',
    timestamp: '2026-09-29 16:40 EAT',
    type: 'Wastage',
    productName: 'Kinangop Roma Tomatoes (Grade 1)',
    batchNumber: 'LOT-2609-TOM-A1',
    quantityDelta: -18,
    unit: 'kilograms',
    fromLocation: 'Nairobi Cold Hub A · C1-R02-B04',
    toLocation: 'Cold Hub Spoilage Quarantine',
    actorName: 'Samuel Mutua',
    reason: 'Crate transit bruising sorted out during QC inspection',
  },
  {
    id: 'MOV-304',
    timestamp: '2026-09-29 14:10 EAT',
    type: 'Transfer',
    productName: 'Murang’a Hass Avocados (Export Grade)',
    batchNumber: 'LOT-2609-AVO-M4',
    quantityDelta: 650,
    unit: 'pieces',
    fromLocation: 'Nairobi Cold Hub A',
    toLocation: 'Westlands Cross-Dock C · W1-R04-B02',
    actorName: 'Samuel Mutua',
    reason: 'Pre-staging for Westlands Hotel Morning Run',
  },
];

export const INITIAL_CUSTOMERS: CustomerInstitutionRecord[] = [
  {
    id: 'CUS-101',
    name: 'Nairobi West Hospital Commissary',
    code: 'INST-HOSP-01',
    segment: 'Hospital',
    isInstitutional: true,
    county: 'Nairobi',
    deliveryZone: 'Nairobi South / Lang’ata Corridor',
    procurementContact: 'Dr. Evelyn Njoroge',
    contactRole: 'Head of Nutrition & Catering Procurement',
    phone: '+254 722 991 004',
    email: 'procurement@nairobiwesthospital.or.ke',
    contractRef: 'CNT-2026-NWH-09',
    tenderCycle: 'Annual Framework (Renews Jan 2027)',
    orderCadence: 'Twice Weekly',
    paymentTerms: 'Net 30',
    creditLimitKes: 2500000,
    outstandingBalanceKes: 642800,
    overdueBalanceKes: 0,
    priceTier: 'Institutional Contract',
    status: 'Active',
  },
  {
    id: 'CUS-102',
    name: 'Alliance High School Boarding Kitchen',
    code: 'INST-SCH-04',
    segment: 'School',
    isInstitutional: true,
    county: 'Kiambu',
    deliveryZone: 'Kikuyu / Kiambu Institutional Run',
    procurementContact: 'Mr. Bernard Kariuki',
    contactRole: 'Senior Cateress & Boarding Bursar',
    phone: '+254 734 112 889',
    email: 'bursar@alliancehigh.sc.ke',
    contractRef: 'TND-2026-AHS-TERM3',
    tenderCycle: 'Termly Public Tender (Term 3 Active)',
    orderCadence: 'Weekly',
    paymentTerms: 'Net 45',
    creditLimitKes: 3800000,
    outstandingBalanceKes: 1485000,
    overdueBalanceKes: 295000,
    priceTier: 'Custom Tender',
    status: 'Credit Watch',
  },
  {
    id: 'CUS-103',
    name: 'Sarova Stanley Hotel & Culinary Group',
    code: 'INST-HTL-02',
    segment: 'Hotel',
    isInstitutional: true,
    county: 'Nairobi',
    deliveryZone: 'CBD & Westlands Hospitality Zone',
    procurementContact: 'Chef Lucas Ochieng',
    contactRole: 'Executive Purchasing Chef',
    phone: '+254 710 605 400',
    email: 'fnb.purchasing@sarovahotels.co.ke',
    contractRef: 'CNT-2026-SRV-14',
    tenderCycle: 'Quarterly Fresh Produce SLA',
    orderCadence: 'Daily',
    paymentTerms: 'Net 15',
    creditLimitKes: 1800000,
    outstandingBalanceKes: 318400,
    overdueBalanceKes: 0,
    priceTier: 'Institutional Contract',
    status: 'Active',
  },
  {
    id: 'CUS-104',
    name: 'Starehe Boys’ Centre & Institute',
    code: 'INST-SCH-08',
    segment: 'School',
    isInstitutional: true,
    county: 'Nairobi',
    deliveryZone: 'Pangani / Thika Road Corridor',
    procurementContact: 'Mrs. Esther Wambui',
    contactRole: 'Supplies & Stores Officer',
    phone: '+254 721 309 774',
    email: 'stores@stareheboyscentre.ac.ke',
    contractRef: 'TND-2026-SBC-02',
    tenderCycle: 'Annual Grain & Tubers Contract',
    orderCadence: 'Weekly',
    paymentTerms: 'Net 30',
    creditLimitKes: 2200000,
    outstandingBalanceKes: 512000,
    overdueBalanceKes: 0,
    priceTier: 'Custom Tender',
    status: 'Active',
  },
  {
    id: 'CUS-105',
    name: 'Carnivore & Tamarind Restaurant Group',
    code: 'INST-RST-07',
    segment: 'Restaurant',
    isInstitutional: true,
    county: 'Nairobi',
    deliveryZone: 'Lang’ata / Karen Hospitality',
    procurementContact: 'Anthony Githuku',
    contactRole: 'Group Supply Chain Controller',
    phone: '+254 725 881 209',
    email: 'supplychain@tamarind.co.ke',
    contractRef: 'CNT-2026-TAM-19',
    tenderCycle: 'Bi-Annual Contract (Renewal Due Oct 2026)',
    orderCadence: 'Daily',
    paymentTerms: 'Net 15',
    creditLimitKes: 1500000,
    outstandingBalanceKes: 194500,
    overdueBalanceKes: 0,
    priceTier: 'Institutional Contract',
    status: 'Tender Renewal',
  },
  {
    id: 'CUS-106',
    name: 'Kilimani Walk-In Fresh Mart (Retail Desk)',
    code: 'RET-WLK-01',
    segment: 'Retail Account',
    isInstitutional: false,
    county: 'Nairobi',
    deliveryZone: 'Kilimani / Direct Hub Collection',
    procurementContact: 'Walk-In Cash / M-Pesa Till',
    contactRole: 'Direct Retail Counter',
    phone: '+254 700 123 000',
    email: 'retaildesk@agrodeliveries.co.ke',
    contractRef: 'DIRECT-POS-CASH',
    tenderCycle: 'Immediate Settlement',
    orderCadence: 'Ad-hoc',
    paymentTerms: 'Prepaid / M-Pesa',
    creditLimitKes: 0,
    outstandingBalanceKes: 0,
    overdueBalanceKes: 0,
    priceTier: 'Retail',
    status: 'Active',
  },
];

export const INITIAL_ORDERS: OrderRecord[] = [
  {
    id: 'ORD-001',
    orderNumber: 'ORD-2026-884',
    customerId: 'CUS-101',
    customerName: 'Nairobi West Hospital Commissary',
    customerSegment: 'Hospital',
    channel: 'Institutional Contract',
    status: 'Picking',
    paymentStatus: 'Invoiced (Net 30)',
    orderDate: '2026-09-30',
    deliveryDate: '2026-10-01',
    warehouseName: 'Nairobi Cold Hub A',
    assignedActor: 'Samuel Mutua (Storekeeper)',
    nextStepLabel: 'Complete FEFO Picking & Stage for Packing',
    totalKes: 168900,
    itemsCount: 3,
    items: [
      {
        productId: 'PRD-001',
        productName: 'Kinangop Roma Tomatoes (Grade 1)',
        sku: 'AG-VEG-001',
        unit: 'kilograms',
        quantity: 280,
        allocatedBatch: 'LOT-2609-TOM-A1',
        unitPriceKes: 105,
        pricingTier: 'Institutional',
        lineTotalKes: 29400,
      },
      {
        productId: 'PRD-004',
        productName: 'Mwea Aromatic Pishori Rice (50kg Sack)',
        sku: 'AG-DRY-002',
        unit: 'bags',
        quantity: 10,
        allocatedBatch: 'LOT-2608-RIC-P9',
        unitPriceKes: 10450,
        pricingTier: 'Institutional',
        lineTotalKes: 104500,
      },
      {
        productId: 'PRD-003',
        productName: 'Organic Sukuma Wiki (Collard Greens)',
        sku: 'AG-GRN-012',
        unit: 'bunches',
        quantity: 1000,
        allocatedBatch: 'LOT-2609-SKM-C1',
        unitPriceKes: 35,
        pricingTier: 'Institutional',
        lineTotalKes: 35000,
      },
    ],
    notes: 'Deliver before 06:30 EAT to Hospital Dietetics Receiving Bay.',
  },
  {
    id: 'ORD-002',
    orderNumber: 'ORD-2026-885',
    customerId: 'CUS-102',
    customerName: 'Alliance High School Boarding Kitchen',
    customerSegment: 'School',
    channel: 'Tender Supply',
    status: 'Confirmed',
    paymentStatus: 'Invoiced (Net 30)',
    orderDate: '2026-09-30',
    deliveryDate: '2026-10-01',
    warehouseName: 'Embakasi Dry Bulk B',
    assignedActor: 'Samuel Mutua (Storekeeper)',
    nextStepLabel: 'Release to Warehouse Picking Queue',
    totalKes: 359400,
    itemsCount: 2,
    items: [
      {
        productId: 'PRD-005',
        productName: 'Fortified Sifted Maize Meal (24x2kg Bale)',
        sku: 'AG-DRY-009',
        unit: 'packs',
        quantity: 70,
        allocatedBatch: 'LOT-2609-MZE-B2',
        unitPriceKes: 3720,
        pricingTier: 'Contract',
        lineTotalKes: 260400,
      },
      {
        productId: 'PRD-007',
        productName: 'Nyandarua Shangi Potatoes (Washed & Graded)',
        sku: 'AG-TUB-003',
        unit: 'kilograms',
        quantity: 1600,
        allocatedBatch: 'LOT-2609-POT-N1',
        unitPriceKes: 61.875,
        pricingTier: 'Contract',
        lineTotalKes: 99000,
      },
    ],
    notes: 'Term 3 Week 5 scheduled boarding supply.',
  },
  {
    id: 'ORD-003',
    orderNumber: 'ORD-2026-886',
    customerId: 'CUS-103',
    customerName: 'Sarova Stanley Hotel & Culinary Group',
    customerSegment: 'Hotel',
    channel: 'Recurring Weekly',
    status: 'Packed',
    paymentStatus: 'Invoiced (Net 30)',
    orderDate: '2026-09-30',
    deliveryDate: '2026-09-30',
    warehouseName: 'Westlands Cross-Dock C',
    assignedActor: 'Joseph Omondi (Delivery Driver)',
    nextStepLabel: 'Assign Vehicle & Dispatch Route Run',
    totalKes: 86250,
    itemsCount: 2,
    items: [
      {
        productId: 'PRD-002',
        productName: 'Murang’a Hass Avocados (Export Grade)',
        sku: 'AG-FRT-004',
        unit: 'pieces',
        quantity: 1300,
        allocatedBatch: 'LOT-2609-AVO-M4',
        unitPriceKes: 30,
        pricingTier: 'Institutional',
        lineTotalKes: 39000,
      },
      {
        productId: 'PRD-001',
        productName: 'Kinangop Roma Tomatoes (Grade 1)',
        sku: 'AG-VEG-001',
        unit: 'kilograms',
        quantity: 450,
        allocatedBatch: 'LOT-2609-TOM-A1',
        unitPriceKes: 105,
        pricingTier: 'Institutional',
        lineTotalKes: 47250,
      },
    ],
  },
  {
    id: 'ORD-004',
    orderNumber: 'ORD-2026-881',
    customerId: 'CUS-104',
    customerName: 'Starehe Boys’ Centre & Institute',
    customerSegment: 'School',
    channel: 'Institutional Contract',
    status: 'Dispatched',
    paymentStatus: 'Invoiced (Net 30)',
    orderDate: '2026-09-29',
    deliveryDate: '2026-09-30',
    warehouseName: 'Embakasi Dry Bulk B',
    assignedActor: 'Joseph Omondi (Delivery Driver)',
    nextStepLabel: 'Capture Electronic Proof of Delivery (POD)',
    totalKes: 209000,
    itemsCount: 1,
    items: [
      {
        productId: 'PRD-004',
        productName: 'Mwea Aromatic Pishori Rice (50kg Sack)',
        sku: 'AG-DRY-002',
        unit: 'bags',
        quantity: 20,
        allocatedBatch: 'LOT-2608-RIC-P9',
        unitPriceKes: 10450,
        pricingTier: 'Contract',
        lineTotalKes: 209000,
      },
    ],
  },
  {
    id: 'ORD-005',
    orderNumber: 'ORD-2026-879',
    customerId: 'CUS-105',
    customerName: 'Carnivore & Tamarind Restaurant Group',
    customerSegment: 'Restaurant',
    channel: 'Institutional Contract',
    status: 'Delivered',
    paymentStatus: 'Paid',
    orderDate: '2026-09-28',
    deliveryDate: '2026-09-29',
    warehouseName: 'Nairobi Cold Hub A',
    assignedActor: 'Completed (POD Verified)',
    nextStepLabel: 'Ready to Close Order',
    totalKes: 116250,
    itemsCount: 1,
    items: [
      {
        productId: 'PRD-006',
        productName: 'Limuru Farm Fresh Tray Eggs (30-Egg Tray)',
        sku: 'AG-DRY-015',
        unit: 'dozens',
        quantity: 250,
        allocatedBatch: 'LOT-2609-EGG-L1',
        unitPriceKes: 465,
        pricingTier: 'Institutional',
        lineTotalKes: 116250,
      },
    ],
  },
];

export const INITIAL_SUPPLIERS: SupplierRecord[] = [
  {
    id: 'SUP-01',
    code: 'VND-KIN-001',
    name: 'Kinangop Highland Growers Co-op',
    category: 'Fresh Vegetables & Tubers',
    region: 'Nyandarua County',
    contactPerson: 'Stephen Njuguna',
    phone: '+254 722 601 882',
    email: 'dispatch@kinangopgrowers.co.ke',
    leadTimeDays: 1,
    paymentTerms: 'Net 14',
    payableBalanceKes: 418000,
    qualityScorePct: 97.4,
    recentPriceTrend: 'Increased +6%',
    status: 'Active',
    suppliedProducts: [
      {
        productId: 'PRD-001',
        productName: 'Kinangop Roma Tomatoes (Grade 1)',
        unit: 'kilograms',
        currentCostKes: 78,
        previousCostKes: 72,
        lastUpdated: '2026-09-20',
      },
      {
        productId: 'PRD-007',
        productName: 'Nyandarua Shangi Potatoes (Washed & Graded)',
        unit: 'kilograms',
        currentCostKes: 46,
        previousCostKes: 45,
        lastUpdated: '2026-09-18',
      },
    ],
    contracts: [
      {
        id: 'CTR-KIN-2026-01',
        contractRef: 'ADK-SC-2026-004',
        title: 'Highland Root Crops & Solanaceous Supply Master Agreement',
        startDate: '2026-01-01',
        endDate: '2026-12-31',
        status: 'Active',
        valueKes: 4500000,
        paymentTerms: 'Net 14',
        deliveryCadence: 'Tri-Weekly to Nairobi Cold Hub A',
        signedDate: '2025-12-20',
        notes: 'Guaranteed minimum monthly offtake of 12,000 kg Roma Tomatoes and 25,000 kg Shangi Potatoes.',
      },
      {
        id: 'CTR-KIN-2026-02',
        contractRef: 'ADK-SC-2026-089',
        title: 'Emergency Seed Potato & Season Buffer Rider',
        startDate: '2026-06-01',
        endDate: '2026-10-31',
        status: 'Expiring Soon',
        valueKes: 1200000,
        paymentTerms: 'Net 14',
        deliveryCadence: 'On Demand',
        signedDate: '2026-05-28',
        notes: 'Seasonal cold buffer reserve for institutional school supply.',
      },
    ],
    documents: [
      {
        id: 'DOC-SUP-01-1',
        docNumber: 'KEBS-AGR-2026-8819',
        title: 'KEBS Standardization Mark of Quality (Fresh Produce)',
        category: 'KEBS Certificate',
        issueDate: '2026-01-15',
        expiryDate: '2027-01-14',
        status: 'Verified',
        fileSize: '1.8 MB PDF',
      },
      {
        id: 'DOC-SUP-01-2',
        docNumber: 'KRA-PIN-P051288491M',
        title: 'KRA Tax Compliance Certificate & Withholding Exemption',
        category: 'Tax Compliance (KRA PIN)',
        issueDate: '2026-03-01',
        expiryDate: '2027-02-28',
        status: 'Verified',
        fileSize: '820 KB PDF',
      },
      {
        id: 'DOC-SUP-01-3',
        docNumber: 'NYA-AGR-PHY-042',
        title: 'County Phytosanitary Clearance & Farm Inspection Report',
        category: 'Phytosanitary Inspection',
        issueDate: '2026-06-10',
        expiryDate: '2026-12-10',
        status: 'Verified',
        fileSize: '2.4 MB PDF',
      },
    ],
    evaluations: [
      {
        id: 'EVL-SUP-01-1',
        evaluationDate: '2026-09-15',
        evaluator: 'David Mwangi (Procurement Officer)',
        overallScorePct: 97.4,
        qualityScorePct: 98.0,
        timelinessScorePct: 96.5,
        pricingCompliancePct: 97.7,
        packagingGrade: 'Grade A',
        notes: 'Outstanding produce sorting, washing, and crate stacking. High farmgate reliability despite Waiyaki corridor transport bottlenecks.',
        recommendation: 'Preferred Cooperative',
      },
      {
        id: 'EVL-SUP-01-2',
        evaluationDate: '2026-06-20',
        evaluator: 'Wanjiku Kamau (Operations Manager)',
        overallScorePct: 96.0,
        qualityScorePct: 97.0,
        timelinessScorePct: 95.0,
        pricingCompliancePct: 96.0,
        packagingGrade: 'Grade A',
        notes: 'Mid-year audit concluded with zero quarantine infractions.',
        recommendation: 'Preferred Cooperative',
      },
    ],
  },
  {
    id: 'SUP-02',
    code: 'VND-MWE-002',
    name: 'Mwea Pishori Rice Millers Ltd',
    category: 'Dry Grains & Cereals',
    region: 'Kirinyaga County',
    contactPerson: 'Catherine Wamuyu',
    phone: '+254 733 910 445',
    email: 'orders@mwearicemillers.co.ke',
    leadTimeDays: 2,
    paymentTerms: 'Net 30',
    payableBalanceKes: 910000,
    qualityScorePct: 99.1,
    recentPriceTrend: 'Stable',
    status: 'Active',
    suppliedProducts: [
      {
        productId: 'PRD-004',
        productName: 'Mwea Aromatic Pishori Rice (50kg Sack)',
        unit: 'bags',
        currentCostKes: 9100,
        previousCostKes: 9100,
        lastUpdated: '2026-09-01',
      },
    ],
    contracts: [
      {
        id: 'CTR-MWE-2026-01',
        contractRef: 'ADK-SC-2026-012',
        title: 'Mwea Grain Milling & Bulk Storage Supply Agreement',
        startDate: '2026-02-01',
        endDate: '2027-01-31',
        status: 'Active',
        valueKes: 10800000,
        paymentTerms: 'Net 30',
        deliveryCadence: 'Bi-Weekly 500-Bag Cross-Docking',
        signedDate: '2026-01-25',
        notes: 'Pure aromatic graded Grade 1 rice with moisture content ≤ 13.0%.',
      },
    ],
    documents: [
      {
        id: 'DOC-SUP-02-1',
        docNumber: 'KEBS-GRN-09822',
        title: 'KEBS Diamond Mark of Quality (Milled White Rice)',
        category: 'KEBS Certificate',
        issueDate: '2025-11-10',
        expiryDate: '2026-11-09',
        status: 'Verified',
        fileSize: '1.2 MB PDF',
      },
      {
        id: 'DOC-SUP-02-2',
        docNumber: 'KRG-TRD-2026-44',
        title: 'Kirinyaga County Industrial Milling & Trading License',
        category: 'County Trade License',
        issueDate: '2026-01-08',
        expiryDate: '2026-12-31',
        status: 'Verified',
        fileSize: '950 KB PDF',
      },
    ],
    evaluations: [
      {
        id: 'EVL-SUP-02-1',
        evaluationDate: '2026-08-30',
        evaluator: 'David Mwangi (Procurement Officer)',
        overallScorePct: 99.1,
        qualityScorePct: 99.5,
        timelinessScorePct: 99.0,
        pricingCompliancePct: 98.8,
        packagingGrade: 'Grade A',
        notes: 'Exceptional milling uniformity. Bag seals intact with zero weevil infestation or broken grain variance.',
        recommendation: 'Preferred Cooperative',
      },
    ],
  },
  {
    id: 'SUP-03',
    code: 'VND-MRG-003',
    name: 'Meru & Murang’a Orchard Union',
    category: 'Fruits & Orchard',
    region: 'Murang’a County',
    contactPerson: 'Patrick Macharia',
    phone: '+254 712 409 318',
    email: 'sales@murangaorchards.co.ke',
    leadTimeDays: 1,
    paymentTerms: 'Net 14',
    payableBalanceKes: 189000,
    qualityScorePct: 95.8,
    recentPriceTrend: 'Decreased -4%',
    status: 'Active',
    suppliedProducts: [
      {
        productId: 'PRD-002',
        productName: 'Murang’a Hass Avocados (Export Grade)',
        unit: 'pieces',
        currentCostKes: 21,
        previousCostKes: 22,
        lastUpdated: '2026-09-10',
      },
    ],
    contracts: [
      {
        id: 'CTR-MRG-2026-01',
        contractRef: 'ADK-SC-2026-027',
        title: 'Hass & Fuerte Avocado Seasonal Offtake Agreement',
        startDate: '2026-03-01',
        endDate: '2026-11-30',
        status: 'Active',
        valueKes: 2800000,
        paymentTerms: 'Net 14',
        deliveryCadence: 'Weekly Harvest Run',
        signedDate: '2026-02-22',
        notes: 'Dry matter content ≥ 23% confirmed prior to packhouse dispatch.',
      },
    ],
    documents: [
      {
        id: 'DOC-SUP-03-1',
        docNumber: 'HCDA-EXP-2026-091',
        title: 'Horticultural Crops Directorate (HCD) Packhouse Registration',
        category: 'Phytosanitary Inspection',
        issueDate: '2026-02-14',
        expiryDate: '2027-02-13',
        status: 'Verified',
        fileSize: '1.5 MB PDF',
      },
    ],
    evaluations: [
      {
        id: 'EVL-SUP-03-1',
        evaluationDate: '2026-09-05',
        evaluator: 'Wanjiku Kamau (Operations Manager)',
        overallScorePct: 95.8,
        qualityScorePct: 96.0,
        timelinessScorePct: 95.0,
        pricingCompliancePct: 96.4,
        packagingGrade: 'Grade A',
        notes: 'Fruit sizing within tight grade specifications. Prompt pricing concession passed down during peak harvest.',
        recommendation: 'Standard Approved',
      },
    ],
  },
  {
    id: 'SUP-04',
    code: 'VND-UNG-004',
    name: 'Unga Bora Rift Millers',
    category: 'Dry Grains & Cereals',
    region: 'Uasin Gishu / Eldoret',
    contactPerson: 'Hillary Koech',
    phone: '+254 720 889 102',
    email: 'b2b@ungaboramillers.co.ke',
    leadTimeDays: 3,
    paymentTerms: 'Net 30',
    payableBalanceKes: 493500,
    qualityScorePct: 98.2,
    recentPriceTrend: 'Stable',
    status: 'Active',
    suppliedProducts: [
      {
        productId: 'PRD-005',
        productName: 'Fortified Sifted Maize Meal (24x2kg Bale)',
        unit: 'packs',
        currentCostKes: 3290,
        previousCostKes: 3290,
        lastUpdated: '2026-09-05',
      },
    ],
    contracts: [
      {
        id: 'CTR-UNG-2026-01',
        contractRef: 'ADK-SC-2026-031',
        title: 'Fortified Maize Flour & Granary Supply Agreement',
        startDate: '2026-01-15',
        endDate: '2026-12-31',
        status: 'Active',
        valueKes: 5900000,
        paymentTerms: 'Net 30',
        deliveryCadence: 'Monthly Bulk Shipment via Rift Railway / Truck',
        signedDate: '2026-01-10',
        notes: 'Fortification compliance with Ministry of Health vitamin micronutrient guidelines.',
      },
    ],
    documents: [
      {
        id: 'DOC-SUP-04-1',
        docNumber: 'KEBS-MZM-88301',
        title: 'KEBS Quality Fortification Certificate',
        category: 'KEBS Certificate',
        issueDate: '2026-01-10',
        expiryDate: '2027-01-09',
        status: 'Verified',
        fileSize: '1.4 MB PDF',
      },
    ],
    evaluations: [
      {
        id: 'EVL-SUP-04-1',
        evaluationDate: '2026-07-28',
        evaluator: 'David Mwangi (Procurement Officer)',
        overallScorePct: 98.2,
        qualityScorePct: 98.5,
        timelinessScorePct: 97.5,
        pricingCompliancePct: 98.6,
        packagingGrade: 'Grade A',
        notes: 'Consistent moisture levels and tamper-evident bale stitching.',
        recommendation: 'Preferred Cooperative',
      },
    ],
  },
  {
    id: 'SUP-05',
    code: 'VND-NAI-005',
    name: 'Naivasha Hydroponics & Herbs Hub',
    category: 'Fresh Vegetables & Herbs',
    region: 'Nakuru County',
    contactPerson: 'Wycliffe Ochieng',
    phone: '+254 711 502 918',
    email: 'supply@naivashahydro.co.ke',
    leadTimeDays: 1,
    paymentTerms: 'Net 14',
    payableBalanceKes: 0,
    qualityScorePct: 94.0,
    recentPriceTrend: 'Stable',
    status: 'Under Review',
    suppliedProducts: [
      {
        productId: 'PRD-003',
        productName: 'English Cucumbers & Rosemary Bundles',
        unit: 'kilograms',
        currentCostKes: 95,
        previousCostKes: 95,
        lastUpdated: '2026-09-28',
      },
    ],
    contracts: [
      {
        id: 'CTR-NAI-2026-01',
        contractRef: 'ADK-SC-2026-102',
        title: 'Hydroponic Salad Greens & Culinary Herbs Pilot Agreement',
        startDate: '2026-10-01',
        endDate: '2027-03-31',
        status: 'Pending Review',
        valueKes: 1600000,
        paymentTerms: 'Net 14',
        deliveryCadence: 'Twice Weekly Cold Transit',
        signedDate: '2026-09-25',
        notes: 'Awaiting formal governance sign-off and site water testing confirmation.',
      },
    ],
    documents: [
      {
        id: 'DOC-SUP-05-1',
        docNumber: 'NAK-ENV-2026-77',
        title: 'County Public Health & Food Handling Clearance',
        category: 'County Trade License',
        issueDate: '2026-09-10',
        expiryDate: '2027-09-09',
        status: 'Pending Verification',
        fileSize: '1.1 MB PDF',
      },
    ],
    evaluations: [
      {
        id: 'EVL-SUP-05-1',
        evaluationDate: '2026-09-29',
        evaluator: 'David Mwangi (Procurement Officer)',
        overallScorePct: 94.0,
        qualityScorePct: 95.0,
        timelinessScorePct: 93.0,
        pricingCompliancePct: 94.0,
        packagingGrade: 'Grade B',
        notes: 'Initial test batch passed microbial swab tests. Greenhouse climate control verified.',
        recommendation: 'Standard Approved',
      },
    ],
  },
  {
    id: 'SUP-06',
    code: 'VND-LIM-006',
    name: 'Limuru Valley Greens Ltd',
    category: 'Leafy Greens',
    region: 'Kiambu County',
    contactPerson: 'Grace Wambui',
    phone: '+254 723 118 903',
    email: 'info@limurugreens.co.ke',
    leadTimeDays: 2,
    paymentTerms: 'Net 7',
    payableBalanceKes: 75000,
    qualityScorePct: 78.5,
    recentPriceTrend: 'Increased +6%',
    status: 'Suspended',
    suspendedReason: 'Failed pesticide residue and cold delivery threshold test on Wk 38.',
    suppliedProducts: [
      {
        productId: 'PRD-006',
        productName: 'Sukuma Wiki & Traditional Managu',
        unit: 'kilograms',
        currentCostKes: 38,
        previousCostKes: 35,
        lastUpdated: '2026-09-14',
      },
    ],
    contracts: [
      {
        id: 'CTR-LIM-2026-01',
        contractRef: 'ADK-SC-2025-055',
        title: 'Daily Leafy Greens School Supply Agreement',
        startDate: '2025-09-01',
        endDate: '2026-08-31',
        status: 'Expired',
        valueKes: 2100000,
        paymentTerms: 'Net 7',
        deliveryCadence: 'Daily 05:00 EAT Morning Run',
        signedDate: '2025-08-20',
        notes: 'Contract suspended pending soil remediation and GAP certification re-audit.',
      },
    ],
    documents: [
      {
        id: 'DOC-SUP-06-1',
        docNumber: 'KEBS-EXP-0012',
        title: 'KEBS Expired Compliance Audit Notice',
        category: 'KEBS Certificate',
        issueDate: '2025-08-01',
        expiryDate: '2026-08-01',
        status: 'Expired',
        fileSize: '750 KB PDF',
      },
    ],
    evaluations: [
      {
        id: 'EVL-SUP-06-1',
        evaluationDate: '2026-09-22',
        evaluator: 'Wanjiku Kamau (Operations Manager)',
        overallScorePct: 78.5,
        qualityScorePct: 74.0,
        timelinessScorePct: 82.0,
        pricingCompliancePct: 79.5,
        packagingGrade: 'Grade C',
        notes: 'Repeated wilting upon arrival at Nairobi Cold Hub A. Temperature logger logged 16°C in transit.',
        recommendation: 'Suspended',
      },
    ],
  },
];

export const INITIAL_PROCUREMENT_ORDERS: ProcurementOrderRecord[] = [
  {
    id: 'PO-01',
    poNumber: 'PO-2026-514',
    prNumber: 'PR-2026-309',
    supplierId: 'SUP-01',
    supplierName: 'Kinangop Highland Growers Co-op',
    warehouseName: 'Nairobi Cold Hub A',
    stage: 'Receiving (GRN)',
    expectedDate: '2026-09-30',
    totalKes: 138800,
    itemsSummary: '600 kg Roma Tomatoes · 2,000 kg Shangi Potatoes',
    qualityCheckPassPct: 97.8,
    requestedBy: 'Peter Ndung’u',
  },
  {
    id: 'PO-02',
    poNumber: 'PO-2026-515',
    prNumber: 'PR-2026-310',
    supplierId: 'SUP-02',
    supplierName: 'Mwea Pishori Rice Millers Ltd',
    warehouseName: 'Embakasi Dry Bulk B',
    stage: 'Pending Approval',
    expectedDate: '2026-10-02',
    totalKes: 910000,
    itemsSummary: '100 bags (50kg) Mwea Aromatic Pishori Rice',
    requestedBy: 'Peter Ndung’u',
  },
  {
    id: 'PO-03',
    poNumber: 'PO-2026-516',
    prNumber: 'PR-2026-311',
    supplierId: 'SUP-03',
    supplierName: 'Meru & Murang’a Orchard Union',
    warehouseName: 'Westlands Cross-Dock C',
    stage: 'PO Issued',
    expectedDate: '2026-10-01',
    totalKes: 25200,
    itemsSummary: '1,200 pcs Murang’a Hass Avocados (Export Grade)',
    requestedBy: 'Peter Ndung’u',
  },
  {
    id: 'PO-04',
    poNumber: 'PO-2026-511',
    prNumber: 'PR-2026-304',
    supplierId: 'SUP-04',
    supplierName: 'Unga Bora Rift Millers',
    warehouseName: 'Embakasi Dry Bulk B',
    stage: 'Stock Posted',
    expectedDate: '2026-09-28',
    totalKes: 493500,
    itemsSummary: '150 bales Fortified Sifted Maize Meal (24x2kg)',
    qualityCheckPassPct: 99.5,
    requestedBy: 'Peter Ndung’u',
  },
];

export const INITIAL_DELIVERIES: DeliveryRunRecord[] = [
  {
    id: 'RUN-01',
    runNumber: 'RUN-2026-0930-A',
    routeZone: 'Pangani & Thika Road Institutional Corridor',
    vehicleReg: 'KDK 482Z (Isuzu Refrigerated 5T)',
    driverName: 'Joseph Omondi',
    driverPhone: '+254 701 445 872',
    departureTime: '06:15 EAT',
    status: 'Dispatched',
    ordersIncluded: ['ORD-2026-881'],
    institutionsServed: ['Starehe Boys’ Centre & Institute'],
    totalWeightKg: 1000,
    podCaptured: false,
  },
  {
    id: 'RUN-02',
    runNumber: 'RUN-2026-0930-B',
    routeZone: 'CBD & Westlands Hospitality Zone',
    vehicleReg: 'KDM 119P (Mitsubishi Canter Cold Box)',
    driverName: 'Joseph Omondi',
    driverPhone: '+254 701 445 872',
    departureTime: '15:00 EAT',
    status: 'Loaded',
    ordersIncluded: ['ORD-2026-886'],
    institutionsServed: ['Sarova Stanley Hotel & Culinary Group'],
    totalWeightKg: 740,
    podCaptured: false,
  },
  {
    id: 'RUN-03',
    runNumber: 'RUN-2026-1001-A',
    routeZone: 'Kikuyu & Kiambu Boarding Schools Run',
    vehicleReg: 'KDJ 904M (Fuso Fighter 10T Dry Bulk)',
    driverName: 'David Karanja',
    driverPhone: '+254 723 611 098',
    departureTime: '05:30 EAT (Scheduled)',
    status: 'Planned',
    ordersIncluded: ['ORD-2026-885', 'ORD-2026-884'],
    institutionsServed: ['Alliance High School Boarding Kitchen', 'Nairobi West Hospital Commissary'],
    totalWeightKg: 5480,
    podCaptured: false,
  },
  {
    id: 'RUN-04',
    runNumber: 'RUN-2026-0929-C',
    routeZone: 'Lang’ata & Karen Hospitality Run',
    vehicleReg: 'KDK 482Z (Isuzu Refrigerated 5T)',
    driverName: 'Joseph Omondi',
    driverPhone: '+254 701 445 872',
    departureTime: '06:00 EAT',
    status: 'Delivered',
    ordersIncluded: ['ORD-2026-879'],
    institutionsServed: ['Carnivore & Tamarind Restaurant Group'],
    totalWeightKg: 420,
    podCaptured: true,
    recipientSignOff: 'Anthony Githuku · Signed 07:42 EAT',
  },
];

export const INITIAL_INVOICES: InvoiceRecord[] = [
  {
    id: 'INV-01',
    invoiceNumber: 'INV-2026-9041',
    orderNumber: 'ORD-2026-884',
    customerId: 'CUS-101',
    customerName: 'Nairobi West Hospital Commissary',
    issueDate: '2026-09-30',
    dueDate: '2026-10-30',
    amountKes: 168900,
    paidAmountKes: 0,
    balanceKes: 168900,
    status: 'Issued',
    agingBucket: 'Current (0-15d)',
  },
  {
    id: 'INV-02',
    invoiceNumber: 'INV-2026-8892',
    orderNumber: 'ORD-2026-840',
    customerId: 'CUS-102',
    customerName: 'Alliance High School Boarding Kitchen',
    issueDate: '2026-08-05',
    dueDate: '2026-09-19',
    amountKes: 595000,
    paidAmountKes: 300000,
    balanceKes: 295000,
    status: 'Overdue',
    agingBucket: '31-60 Days',
  },
  {
    id: 'INV-03',
    invoiceNumber: 'INV-2026-8990',
    orderNumber: 'ORD-2026-871',
    customerId: 'CUS-103',
    customerName: 'Sarova Stanley Hotel & Culinary Group',
    issueDate: '2026-09-20',
    dueDate: '2026-10-05',
    amountKes: 318400,
    paidAmountKes: 0,
    balanceKes: 318400,
    status: 'Issued',
    agingBucket: 'Current (0-15d)',
  },
  {
    id: 'INV-04',
    invoiceNumber: 'INV-2026-9012',
    orderNumber: 'ORD-2026-879',
    customerId: 'CUS-105',
    customerName: 'Carnivore & Tamarind Restaurant Group',
    issueDate: '2026-09-28',
    dueDate: '2026-10-13',
    amountKes: 116250,
    paidAmountKes: 116250,
    balanceKes: 0,
    status: 'Paid',
    agingBucket: 'Current (0-15d)',
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'PAY-01',
    referenceCode: 'QIT89K2M4P (M-Pesa Paybill 542900)',
    direction: 'Inbound (Customer AR)',
    counterpartyName: 'Carnivore & Tamarind Restaurant Group',
    method: 'M-Pesa Paybill',
    date: '2026-09-29',
    amountKes: 116250,
    allocatedToDoc: 'INV-2026-9012',
    reconciled: true,
    recordedBy: 'Faith Chebet',
  },
  {
    id: 'PAY-02',
    referenceCode: 'KCB-RTGS-20260927-881',
    direction: 'Inbound (Customer AR)',
    counterpartyName: 'Alliance High School Boarding Kitchen',
    method: 'Bank EFT / RTGS',
    date: '2026-09-27',
    amountKes: 300000,
    allocatedToDoc: 'INV-2026-8892',
    reconciled: true,
    recordedBy: 'Faith Chebet',
  },
  {
    id: 'PAY-03',
    referenceCode: 'EQB-EFT-20260926-409',
    direction: 'Outbound (Supplier AP)',
    counterpartyName: 'Kinangop Highland Growers Co-op',
    method: 'Bank EFT / RTGS',
    date: '2026-09-26',
    amountKes: 245000,
    allocatedToDoc: 'PO-2026-508',
    reconciled: true,
    recordedBy: 'Mercy Kamau',
  },
  {
    id: 'PAY-04',
    referenceCode: 'MPESA-B2B-994012A',
    direction: 'Inbound (Customer AR)',
    counterpartyName: 'Nairobi West Hospital Commissary',
    method: 'M-Pesa Paybill',
    date: '2026-09-30',
    amountKes: 185000,
    allocatedToDoc: 'INV-2026-8955',
    reconciled: false,
    recordedBy: 'Faith Chebet',
  },
];

export const INITIAL_CRM_TICKETS: CrmTicketRecord[] = [
  {
    id: 'CRM-01',
    ticketNumber: 'TKT-2026-108',
    customerName: 'Carnivore & Tamarind Restaurant Group',
    type: 'Contract Renewal',
    priority: 'High',
    status: 'In Progress',
    assignedTo: 'Grace Achieng',
    dueDate: '2026-10-05',
    summary: 'Q4-Q1 Bi-Annual Fresh Produce & Eggs SLA renewal negotiation (+8% volume commitment).',
  },
  {
    id: 'CRM-02',
    ticketNumber: 'TKT-2026-109',
    customerName: 'Alliance High School Boarding Kitchen',
    type: 'Tender Pricing Inquiry',
    priority: 'Medium',
    status: 'Open',
    assignedTo: 'Grace Achieng',
    dueDate: '2026-10-03',
    summary: 'Request for supplementary dry yellow beans & fortification certificate for October midterm.',
  },
  {
    id: 'CRM-03',
    ticketNumber: 'TKT-2026-104',
    customerName: 'Nairobi West Hospital Commissary',
    type: 'Delivery Window Change',
    priority: 'Normal',
    status: 'Resolved',
    assignedTo: 'Daniel Kiprop',
    dueDate: '2026-09-29',
    summary: 'Updated morning receiving window to 06:00–06:45 EAT for cold-chain produce.',
  },
];

export const INITIAL_APPROVALS: ApprovalRequestRecord[] = [
  {
    id: 'APR-01',
    reference: 'PO-2026-515',
    category: 'Purchase Order',
    entityTitle: 'Mwea Pishori Rice Millers · 100 Bags (50kg) Replenishment',
    requesterName: 'Peter Ndung’u',
    requesterRole: 'Procurement Officer',
    valueKes: 910000,
    reason: 'Replenish Embakasi Dry Bulk B ahead of October Term 3 school & hospital deliveries.',
    requestedAt: '2026-09-30 10:15 EAT',
    status: 'Pending',
  },
  {
    id: 'APR-02',
    reference: 'OVR-2026-042',
    category: 'Credit Limit Extension',
    entityTitle: 'Alliance High School Boarding Kitchen · Temporary Term 3 Release',
    requesterName: 'Grace Achieng',
    requesterRole: 'Sales Representative',
    valueKes: 359400,
    reason: 'Ministry capitation tranche expected Oct 6; school requires uninterrupted boarding maize meal supply.',
    requestedAt: '2026-09-30 11:02 EAT',
    status: 'Pending',
  },
  {
    id: 'APR-03',
    reference: 'WST-2026-019',
    category: 'Inventory Wastage Write-Off',
    entityTitle: 'LOT-2609-TOM-A1 · 18kg Roma Tomatoes Transit Bruising',
    requesterName: 'Samuel Mutua',
    requesterRole: 'Storekeeper',
    valueKes: 1404,
    reason: 'Separated bruised fruit during cold-room FEFO sorting to protect hospital quality SLA.',
    requestedAt: '2026-09-29 16:45 EAT',
    status: 'Approved',
    decisionBy: 'Daniel Kiprop',
    decisionComment: 'Verified against QC inspection photo log.',
    decisionAt: '2026-09-29 17:10 EAT',
  },
];

export const INITIAL_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'DOC-01',
    docNumber: 'DOC-2026-884-INV',
    title: 'Commercial Tax Invoice INV-2026-9041 (Nairobi West Hospital)',
    category: 'Invoice',
    linkedEntity: 'ORD-2026-884',
    uploadedBy: 'Faith Chebet',
    uploadedAt: '2026-09-30',
    fileSize: '248 KB',
    storageBucket: 'bos-finance-invoices',
    verified: true,
  },
  {
    id: 'DOC-02',
    docNumber: 'DOC-2026-412-GRN',
    title: 'Goods Received Note GRN-2026-412 (Kiambu Peri-Urban Greens)',
    category: 'Goods Received Note (GRN)',
    linkedEntity: 'LOT-2609-SKM-C1',
    uploadedBy: 'Samuel Mutua',
    uploadedAt: '2026-09-30',
    fileSize: '412 KB',
    storageBucket: 'bos-warehouse-grn',
    verified: true,
  },
  {
    id: 'DOC-03',
    docNumber: 'DOC-2026-879-POD',
    title: 'Signed Electronic POD · Carnivore & Tamarind Group',
    category: 'Proof of Delivery (POD)',
    linkedEntity: 'RUN-2026-0929-C',
    uploadedBy: 'Joseph Omondi',
    uploadedAt: '2026-09-29',
    fileSize: '615 KB',
    storageBucket: 'bos-logistics-pod',
    verified: true,
  },
  {
    id: 'DOC-04',
    docNumber: 'DOC-2026-KEBS-MZE',
    title: 'KEBS Vitamin Fortification & Aflatoxin Clearance Certificate',
    category: 'KEBS / Quality Certificate',
    linkedEntity: 'LOT-2609-MZE-B2',
    uploadedBy: 'Peter Ndung’u',
    uploadedAt: '2026-09-12',
    fileSize: '1.1 MB',
    storageBucket: 'bos-compliance-certs',
    verified: true,
  },
  {
    id: 'DOC-05',
    docNumber: 'DOC-2026-881-DN',
    title: 'Institutional Delivery Note DN-881 (Starehe Boys’ Centre)',
    category: 'Delivery Note',
    linkedEntity: 'ORD-2026-881',
    uploadedBy: 'Samuel Mutua',
    uploadedAt: '2026-09-29',
    fileSize: '192 KB',
    storageBucket: 'bos-logistics-dn',
    verified: true,
  },
  {
    id: 'DOC-06',
    docNumber: 'DOC-2026-515-PO',
    title: 'Draft Purchase Order PO-2026-515 (Mwea Pishori Rice Millers)',
    category: 'Purchase Order',
    linkedEntity: 'PO-2026-515',
    uploadedBy: 'Peter Ndung’u',
    uploadedAt: '2026-09-30',
    fileSize: '310 KB',
    storageBucket: 'bos-procurement-po',
    verified: false,
  },
  {
    id: 'DOC-07',
    docNumber: 'DOC-2026-SUP-KIN',
    title: 'Kinangop Growers Cooperative GlobalG.A.P. Phytosanitary Dossier',
    category: 'Supplier Document',
    linkedEntity: 'VND-KIN-001',
    uploadedBy: 'Peter Ndung’u',
    uploadedAt: '2026-09-15',
    fileSize: '1.8 MB',
    storageBucket: 'bos-supplier-dossiers',
    verified: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogRecord[] = [
  {
    id: 'AUD-9001',
    timestamp: '2026-09-30 12:04:18 EAT',
    actorName: 'Samuel Mutua',
    actorRole: 'Storekeeper',
    actorEmail: 's.mutua@agrodeliveries.co.ke',
    module: 'Fulfillment',
    entity: 'Order ORD-2026-884',
    action: 'FEFO Batch Allocated & Status -> Picking',
    beforeValue: 'Status: Confirmed | Batch: Unassigned | Reserved: 0 kg',
    afterValue: 'Status: Picking | Batch: LOT-2609-TOM-A1 (280 kg reserved from Bin C1-R02-B04)',
  },
  {
    id: 'AUD-9002',
    timestamp: '2026-09-30 10:15:42 EAT',
    actorName: 'Peter Ndung’u',
    actorRole: 'Procurement Officer',
    actorEmail: 'p.ndungu@agrodeliveries.co.ke',
    module: 'Procurement',
    entity: 'Purchase Order PO-2026-515',
    action: 'Submitted Purchase Order for Approval',
    beforeValue: 'Stage: Purchase Request (PR-2026-310) | Approval: Not Submitted',
    afterValue: 'Stage: Pending Approval | Value: KES 910,000 (100 bags Mwea Pishori Rice)',
  },
  {
    id: 'AUD-9003',
    timestamp: '2026-09-29 17:10:05 EAT',
    actorName: 'Daniel Kiprop',
    actorRole: 'Operations Manager',
    actorEmail: 'd.kiprop@agrodeliveries.co.ke',
    module: 'Approvals',
    entity: 'Approval WST-2026-019',
    action: 'Approved Inventory Wastage Write-Off',
    beforeValue: 'Status: Pending | Batch: LOT-2609-TOM-A1 | Qty: 18 kg',
    afterValue: 'Status: Approved | Write-off: KES 1,404 | Comment: Verified against QC inspection photo log',
  },
  {
    id: 'AUD-9004',
    timestamp: '2026-09-25 09:00:11 EAT',
    actorName: 'Victor Kinyua',
    actorRole: 'Administrator',
    actorEmail: 'v.kinyua@agrodeliveries.co.ke',
    module: 'Administration',
    entity: 'User USR-010 (Brian Otieno)',
    action: 'Account Status Updated',
    beforeValue: 'Status: Active | Branch: Embakasi Dry Bulk B',
    afterValue: 'Status: Suspended | Reason: Pending physical stock count reconciliation',
  },
  {
    id: 'AUD-9005',
    timestamp: '2026-09-24 15:22:40 EAT',
    actorName: 'Mercy Kamau',
    actorRole: 'Finance Manager',
    actorEmail: 'm.kamau@agrodeliveries.co.ke',
    module: 'Finance',
    entity: 'Settlement KCB-RTGS-20260927-881',
    action: 'Allocated & Reconciled Institutional Payment',
    beforeValue: 'Invoice INV-2026-8892 Balance: KES 595,000 | Reconciled: false',
    afterValue: 'Invoice INV-2026-8892 Balance: KES 295,000 | Paid: KES 300,000 | Reconciled: true',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NTF-01',
    severity: 'Action Required',
    title: '2 FEFO Perishable Batches Expiring Within 72 Hours',
    description: 'LOT-2609-SKM-C1 (Sukuma Wiki, 2 days) and LOT-2609-TOM-A1 (Roma Tomatoes, 3 days) in Nairobi Cold Hub A.',
    timestamp: '12 mins ago',
    href: '/inventory',
    permissionRequired: 'inventory.view',
    read: false,
  },
  {
    id: 'NTF-02',
    severity: 'Action Required',
    title: 'Purchase Order PO-2026-515 Awaiting Approval (KES 910,000)',
    description: '100 bags Mwea Pishori Rice replenishment requested by Peter Ndung’u.',
    timestamp: '45 mins ago',
    href: '/approvals',
    permissionRequired: 'approvals.view',
    read: false,
  },
  {
    id: 'NTF-03',
    severity: 'Warning',
    title: 'Overdue Institutional Balance: Alliance High School (KES 295,000)',
    description: 'Invoice INV-2026-8892 is 11 days past Net 45 terms.',
    timestamp: '2 hours ago',
    href: '/finance',
    permissionRequired: 'finance.view',
    read: false,
  },
  {
    id: 'NTF-04',
    severity: 'Information',
    title: 'Supplier Cost Increase (+6%) on Kinangop Roma Tomatoes',
    description: 'Kinangop Highland Growers Co-op adjusted farmgate cost from KES 72/kg to KES 78/kg.',
    timestamp: '4 hours ago',
    href: '/suppliers',
    permissionRequired: 'suppliers.view',
    read: true,
  },
];
